---
- name: Ensure tmux is installed
  become: yes
  become_user: root
  apt: pkg=tmux state=present
  register: installation

- block:
  - name: Backup tmux config
    become: yes
    become_user: '{{ item }}'
    copy: src={{ tmux }} dest={{ tmux }}.bak remote_src=yes backup=yes
    ignore_errors: yes
    with_items: '{{ users }}'

  - name: Check if ZSH is installed
    stat: path=/usr/bin/zsh
    register: zsh

  - name: Install config [No ZSH]
    become: yes
    become_user: '{{ item }}'
    copy: src=tmux.conf dest={{ tmux }}
    with_items: '{{ users }}'
    when: not zsh.stat.exists

  - name: Install config [ZSH]
    become: yes
    become_user: '{{ item }}'
    copy: src=zsh_tmux.conf dest={{ tmux }}
    with_items: '{{ users }}'
    when: zsh.stat.exists

  when: users is defined and installation is success 