---
- name: Update Grub Config
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - {regex: "^GRUB_TIMEOUT=", line: "GRUB_TIMEOUT=1"}
    - {regex: "^GRUB_CMDLINE_LINUX_DEFAULT=", line: 'GRUB_CMDLINE_LINUX_DEFAULT="vga=0x0318"'}
  register: grubconfig

- name: Update Grub active settings
  command: update-grub
  when: grubconfig.changed