---

- name: Delete old SSH Keys
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ed25519_key

- name: Generate /etc/ssh/ RSA host key
  command: ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N "" -b 4096
  args:
    creates: /etc/ssh/ssh_host_rsa_key
  notify:
    - restart sshd

- name: Generate /etc/ssh DSA host key
  command: ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C "" -N "" -b 1024
  args:
    creates: /etc/ssh/ssh_host_dsa_key
  notify:
    - restart sshd

- name: Generate /etc/ssh ECDSA host key
  command: ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C "" -N "" -b 521
  args:
    creates: /etc/ssh/ssh_host_ecdsa_key
  notify:
    - restart sshd

- name: Generate /etc/ssh ed25519 host key
  command: ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -C "" -N "" -b 512
  args:
    creates: /etc/ssh/ssh_host_ed25519_key
  notify:
    - restart sshd
